apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbreceive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbreceive-app
  template:
    metadata:
      labels:
        app: rbreceive-app
    spec:
      containers:
      - name: rbreceive-container
        image: josesleiter/rabit-send:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: rbreceive-service
spec:
  type: NodePort
  selector:
    app: rbreceive-app
  ports:
  - name: rbreceive-service
    protocol: TCP
    port: 80
    targetPort: 3000
